var namespace_wire_cell_1_1_sig_proc =
[
    [ "Diagnostics", "namespace_wire_cell_1_1_sig_proc_1_1_diagnostics.html", "namespace_wire_cell_1_1_sig_proc_1_1_diagnostics" ],
    [ "Microboone", "namespace_wire_cell_1_1_sig_proc_1_1_microboone.html", "namespace_wire_cell_1_1_sig_proc_1_1_microboone" ],
    [ "Protodune", "namespace_wire_cell_1_1_sig_proc_1_1_protodune.html", "namespace_wire_cell_1_1_sig_proc_1_1_protodune" ],
    [ "ChannelSelector", "class_wire_cell_1_1_sig_proc_1_1_channel_selector.html", "class_wire_cell_1_1_sig_proc_1_1_channel_selector" ],
    [ "ChannelSplitter", "class_wire_cell_1_1_sig_proc_1_1_channel_splitter.html", "class_wire_cell_1_1_sig_proc_1_1_channel_splitter" ],
    [ "CompareRois", "struct_wire_cell_1_1_sig_proc_1_1_compare_rois.html", "struct_wire_cell_1_1_sig_proc_1_1_compare_rois" ],
    [ "DBChannelSelector", "class_wire_cell_1_1_sig_proc_1_1_d_b_channel_selector.html", "class_wire_cell_1_1_sig_proc_1_1_d_b_channel_selector" ],
    [ "FieldResponse", "class_wire_cell_1_1_sig_proc_1_1_field_response.html", "class_wire_cell_1_1_sig_proc_1_1_field_response" ],
    [ "FrameMerger", "class_wire_cell_1_1_sig_proc_1_1_frame_merger.html", "class_wire_cell_1_1_sig_proc_1_1_frame_merger" ],
    [ "FrameSplitter", "class_wire_cell_1_1_sig_proc_1_1_frame_splitter.html", "class_wire_cell_1_1_sig_proc_1_1_frame_splitter" ],
    [ "HfFilter", "class_wire_cell_1_1_sig_proc_1_1_hf_filter.html", "class_wire_cell_1_1_sig_proc_1_1_hf_filter" ],
    [ "L1SPFilter", "class_wire_cell_1_1_sig_proc_1_1_l1_s_p_filter.html", "class_wire_cell_1_1_sig_proc_1_1_l1_s_p_filter" ],
    [ "LfFilter", "class_wire_cell_1_1_sig_proc_1_1_lf_filter.html", "class_wire_cell_1_1_sig_proc_1_1_lf_filter" ],
    [ "NominalChannelResponse", "class_wire_cell_1_1_sig_proc_1_1_nominal_channel_response.html", "class_wire_cell_1_1_sig_proc_1_1_nominal_channel_response" ],
    [ "Omnibus", "class_wire_cell_1_1_sig_proc_1_1_omnibus.html", "class_wire_cell_1_1_sig_proc_1_1_omnibus" ],
    [ "OmnibusNoiseFilter", "class_wire_cell_1_1_sig_proc_1_1_omnibus_noise_filter.html", "class_wire_cell_1_1_sig_proc_1_1_omnibus_noise_filter" ],
    [ "OmnibusPMTNoiseFilter", "class_wire_cell_1_1_sig_proc_1_1_omnibus_p_m_t_noise_filter.html", "class_wire_cell_1_1_sig_proc_1_1_omnibus_p_m_t_noise_filter" ],
    [ "OmnibusSigProc", "class_wire_cell_1_1_sig_proc_1_1_omnibus_sig_proc.html", "class_wire_cell_1_1_sig_proc_1_1_omnibus_sig_proc" ],
    [ "OmniChannelNoiseDB", "class_wire_cell_1_1_sig_proc_1_1_omni_channel_noise_d_b.html", "class_wire_cell_1_1_sig_proc_1_1_omni_channel_noise_d_b" ],
    [ "PeakFinding", "class_wire_cell_1_1_sig_proc_1_1_peak_finding.html", "class_wire_cell_1_1_sig_proc_1_1_peak_finding" ],
    [ "PerChannelResponse", "class_wire_cell_1_1_sig_proc_1_1_per_channel_response.html", "class_wire_cell_1_1_sig_proc_1_1_per_channel_response" ],
    [ "PMTNoiseROI", "class_wire_cell_1_1_sig_proc_1_1_p_m_t_noise_r_o_i.html", "class_wire_cell_1_1_sig_proc_1_1_p_m_t_noise_r_o_i" ],
    [ "ROI_formation", "class_wire_cell_1_1_sig_proc_1_1_r_o_i__formation.html", "class_wire_cell_1_1_sig_proc_1_1_r_o_i__formation" ],
    [ "ROI_refinement", "class_wire_cell_1_1_sig_proc_1_1_r_o_i__refinement.html", "class_wire_cell_1_1_sig_proc_1_1_r_o_i__refinement" ],
    [ "SignalROI", "class_wire_cell_1_1_sig_proc_1_1_signal_r_o_i.html", "class_wire_cell_1_1_sig_proc_1_1_signal_r_o_i" ],
    [ "SimpleChannelNoiseDB", "class_wire_cell_1_1_sig_proc_1_1_simple_channel_noise_d_b.html", "class_wire_cell_1_1_sig_proc_1_1_simple_channel_noise_d_b" ]
];